Shindo.tests do
  test('exception') { raise StandardError.new('exception') }
end